### ISSUE TITLE
Add support for private feeds

### ISSUE THREAD

**Issue by lkarbownik** [chhoumann/PodNotes#16]
Is the support for private/premium podcast feeds on the roadmap for this plugin?

If yes, I would be happy to contribute to the repo (if you are currently accepting contributions).

**Comment by chhoumann** [comment]
Hi, @lkarbownik 

This is already added. 
Paste the feed link into the Podcast search bar and it should try to detect it.

**Comment by lkarbownik** [comment]
I've managed to add private feeds I use by entering the URL in the search bar and pressing Return.

Amazing plugin. Thanks a lot!
