### ISSUE TITLE
FR: timestamp as link to play at that time

### ISSUE THREAD

**Issue by derekvan** [chhoumann/PodNotes#29]
This is fantastic. Thanks for sharing it. One question I have: is it possible to get the local file name for the timestamp template? (I’m mostly using this for local files, not podcasts). I’m hoping to integrate this with Media Player extended. With that plugin, if I have a timestamp in this form, I can click the timestamp link and the player will load up at that time (maybe this could also be a useful feature of PodNotes?):

[[filename.m4a#t=1:15:51|🔈]] (the alias and speaker are just my own flourish for the form, the key is the filename with the hash and timestamp)

**Comment by monstertank** [comment]
i second that
what i observed is that if we adjust url like the below it already works for local files 
if it can be done just like other podcast from internet it would be great
```
obsidian://podnotes?episodeName=audio&url=file:///D:/folder/audio.mp3&time=1096.215603
```

**Comment by chhoumann** [comment]
Hi @derekvan,

Thank you for this suggestion. I've added it as part of 2.5.0, so it now works with `{{linktime}}` on local files. :)
Same workflow as for standard podcasts now.
