### ISSUE TITLE
Podcast episode download not working

### ISSUE THREAD

**Issue by Brigedd0** [chhoumann/PodNotes#31]
I'm trying to download the download the episodes of this podcast https://is.gd/x33vID

I receive the following error message
https://i.postimg.cc/bw5J0cQR/Immagine-2022-09-07-120631.jpg

Those are the settings I'm using
https://i.postimg.cc/dDM6ZS5Q/Immagine-2022-09-07-120757.jpg
https://i.postimg.cc/76FtS66y/Immagine-2022-09-07-120848.jpg

**Comment by danieltomasz** [comment]
Yes, it doesnt work for me too.

**Comment by lorenzlm** [comment]
Same here. I don't even get an error message. It simply doesn't load... The paths are correct, folders installed, I double-checked everything.
<img width="299" alt="Screenshot 2022-09-19 at 00 56 00" src="https://user-images.githubusercontent.com/10097702/190931809-d7f4b3e7-e45f-45a1-bfbb-32c8459390b2.png">

**Comment by diego898** [comment]
Same for me - no error, just stuck on 0%.

**Comment by diego898** [comment]
Ive tried this with both private and public podcast feeds, and on my icloud drive and just my desktop. All cases just a stuck at 0% without other error. Using latest mac osx and 0.15.9 obsidian

**Comment by danieltomasz** [comment]
I was able to download podcast today :) I am on MacOS 13 beta, but I think this has more to do with the service that was used to download the file

**Comment by timmyreal** [comment]
Something similar is going on with me. Some episodes download fine, but others just stay stuck at 0%.

![C4956668-3AB2-4622-8269-AA2027AC7247_1_201_a](https://user-images.githubusercontent.com/82277734/191567330-944ee654-d473-45f6-b0e1-fe7827137d02.jpeg)

**Comment by erauner12** [comment]
Yeah I cannot get anything to work?
<img width="301" alt="image" src="https://user-images.githubusercontent.com/59383957/202789812-915cbd49-1221-4029-87f9-766515ffaa8a.png">


Wonder if has anything if it my download path is in iCloud?

**Comment by chhoumann** [comment]
Seems to have been a policy issue with some providers & grabbing episodes from Obsidian.

Should be resolved now. If you still encounter issues, lmk!
