### ISSUE TITLE
[UX request] Create note button in the  player pane

### ISSUE THREAD

**Issue by danieltomasz** [chhoumann/PodNotes#32]
Thank you for including the palette command to create note!

What would be useful for me would having this button with this function added to the pane (could as something that be turned on/off) when I start playing the podcast, one less step to start notes on the podcast!

Again thanks, your  plugin is amazing :)

**Comment by chhoumann** [comment]
Hey @danieltomasz! Thank you. Glad you like it!

What do you think of the right-click to add note? On the podcast episode thumbnail. This works in any view basically. 

Or is it best if there's a button that instantly creates the note in the player?

**Comment by danieltomasz** [comment]
Hi @chhoumann ! Yes, I didnt know about this!
This will be really usefull for me and solves my problem.

One thing I can still think of, is how to make it more discoverable (maybe by adding it to the documentation or frontpage on github that you could use right-click on podcast minimature to bring a menu).

If I have better a better idea, I will comment here :) 
But you might close this issue :)

**Comment by danieltomasz** [comment]
Maybe just replace png for player with a gif where you first just click on thumbnail to play, but then you could right-click to bring the menu?
