### ISSUE TITLE
[BUG] Templater tp.file.rename & tp.file.move not working  

### ISSUE THREAD

**Issue by shivp436** [chhoumann/PodNotes#38]
![image](https://user-images.githubusercontent.com/66512778/191840283-9934e223-791a-4a7b-a332-6aa71f2cb065.png)

On lines 10 & 11, I have used code to rename the file title which basically **replaces whitespace with underscores in the file name, and line 11 moves the file to a folder dedicated to each podcast** , 
Both of these lines are producing an issue.

Please correct this issue, or release variables {{title_}} and {{podcast_}} which provide data with underscores.

**Comment by chhoumann** [comment]
Added in latest release. You can add a format, e.g. `{{title:_}}` to replace spaces with underscores in the file title.
