### ISSUE TITLE
Light Mode!?!

### ISSUE THREAD

**Issue by davebhc71** [chhoumann/PodNotes#42]
It seems to me that the Plugin may have been developed primarily in Dark mode. I have noticed several visual anomalies while trying to use Light mode that do not ‘appear’ in Dark Mode. One instance is pictured below where black text ‘disappears’  when box is selected OR Mouse hovers.
![IMG_595](https://user-images.githubusercontent.com/80698092/192268346-44ad29b1-3d31-4e85-b0f7-e728268c83fc.jpeg)

**Comment by danieltomasz** [comment]
maybe it doesnt work with your css theme (it is primary?)
The vanilla obsidian and minimal theme work ok, this might be fixed either here or via theme developer

**Comment by chhoumann** [comment]
Seems to have been fixed since I last checked. I just tested it with some of the most popular light themes, and cannot spot any visual bugs like that.

Closing this, but please LMK if I'm missing anything!
