### ISSUE TITLE
When note for podcast is already created, change the 'create note' option into 'go to note'

### ISSUE THREAD

**Issue by base-I** [chhoumann/PodNotes#45]

**Comment by chhoumann** [comment]
Hi @base-I, thank you for the FR.

This is already in the plugin.
![image](https://user-images.githubusercontent.com/29108628/201870566-12a8249a-c130-43e8-a601-178427ddd982.png)

If you have issues with notes not getting detected, please open another issue. 

Best regards,
Christian
