### ISSUE TITLE
UI for iPad and Mac are different?

### ISSUE THREAD

**Issue by davebhc71** [chhoumann/PodNotes#48]
Your demonstration for using the Plugin seems to have a different UI than what I see on the iPad Air plugin panel. Is that by design? I can not make out what the selections are, but I’m sure they are relevant to the usage of the plugin.
Mac-
![0AD66367-818E-4DE8-899F-A6C8935DBA81](https://user-images.githubusercontent.com/80698092/197534252-bee51f56-20dd-4365-8846-f1adc2b8e8ff.jpeg)
IPad-
![ABF84A35-49A6-4AB9-8B59-60181ED4392B](https://user-images.githubusercontent.com/80698092/197534316-7386137f-6772-4439-852b-a43f15296514.jpeg)

**Comment by chhoumann** [comment]
Hi @davebhc71,

What you're seeing in my demo images are part of my own Obsidian UI.
The icons are for default Obsidian features, e.g. backlinks, tags, outline, and so on.

These aren't part of the plugin.

Best regards,
Christian

**Comment by davebhc71** [comment]
Thank you for the reply. Have you had any time for addressing the issue I submitted in #41, where the images of the Podcasts are severely distorted when viewed in a Pinned sidebar pane of an 11” iPad? Thanks in advance for your consideration!On Nov 15, 2022, at 2:15 AM, Christian Bager Bach Houmann ***@***.***> wrote:﻿
Hi @davebhc71,
What you're seeing in my demo images are part of my own Obsidian UI.
The icons are for default Obsidian features, e.g. backlinks, tags, outline, and so on.
These aren't part of the plugin.
Best regards,
Christian
