### ISSUE TITLE
Allow saving podcast note in subfolders based on podcast

### ISSUE THREAD

**Issue by scottmc42** [chhoumann/PodNotes#49]
Not sure if this is a bug or a feature request.

What I am trying to do is separate all the notes into folders based on the podcast name. As it stands right now, I can only choose a single folder and all podcasts get dumped into the same bucket. While I generally don't go looking for a file by looking through the file explorer, it's not a big deal, but the OCD in me still would like segmentation.

Issue:
The `Note creation file path` does not create a path if it does not already exist.

Example:
Setting the file path to `Podcasts/{{podcast}}-{{title}}` will correctly save the file into the `Podcasts` folder, if it exists.

But `Podcasts/{{podcast}}/{{title}}` fails because the first time the user creates a note for any given podcast, `Podcasts/{{podcast}}/` does not exist. So unless the user manually creates a folder that matches the podcast name exactly before hand, the new note will not be created and an error displayed.

Note: Untested, but presumably, the download folder would have the same bug/lack of feature. I couldn't test because all the podcasts I tried to download returned a CORS error.

**Comment by chhoumann** [comment]
This makes sense. I've made the file creation process more flexible, so you can now specify folders that will be created if they don't exist.

The example file path you gave is now possible.

This is available in 2.2.0
