### ISSUE TITLE
Retrieve old podcast entries

### ISSUE THREAD

**Issue by EhuddR** [chhoumann/PodNotes#50]
Hi! I would like to know if it is possible to implement an option to search and play old episodes of a given podcast, that is, let's say I want to play an episode of 2016 to take notes and process the information. At the moment PodNotes only shows the episodes of the last six months.

Maybe it has something to do with the platform from which I collect the information from. 

I attach the loml of the podcast: https://www.ivoox.com/feed_fg_f136870_filtro_1.xml

I congratulate you for your work with this plugin. Thank you very much, 

I look forward to your comments.

Best regards.

**Comment by chhoumann** [comment]
Hi @EhuddR,

Thank you!

Looks like the feed link only provides episodes going back to Sat, 16 Apr 2022.
I looked around a bit, but couldn't find any providers that had any episodes going further back, so I assume it's just the podcast host that doesn't provide them.

Best regards,
Christian
