### ISSUE TITLE
linked time stamps for local files ( manually adjusting url already works ) [enhancement]

### ISSUE THREAD

**Issue by monstertank** [chhoumann/PodNotes#56]
```
obsidian://podnotes?episodeName=audio&url=file:///D:/folder/audio.mp3&time=1096.215603

```

adjusting url as above for local files already works for time stamps

please make it to a core feature to add linked time stamps for local files

thank you for this amazing plugin

**Comment by chhoumann** [comment]
Hi @monstertank,

Thank you for your suggestion. This has been added in 2.5.0!
