### ISSUE TITLE
No podcast browser window

### ISSUE THREAD

**Issue by Matoo125** [chhoumann/PodNotes#61]
Hello, I have installed the plugin, and added few podcasts in the plugin settings. Unfortunatelly, nothing happens when I try to "Play podcast" cannot find the window where I can actually browse my selected podcast.

Using Macbook air with M2. No errors in Obsidian console.

**Comment by chhoumann** [comment]
Hi @Matoo125,

Do you have this command available to you?
![image](https://user-images.githubusercontent.com/29108628/217568735-7405b88f-4c21-4821-9296-18aa6ef075ec.png)

If so, then activating it would make the pane appear. It appears in the right sidebar with an icon denoting playback:
![image](https://user-images.githubusercontent.com/29108628/217569144-23a20047-e75c-4a8b-80c8-36a6b762d449.png)

If you do not have the command accessible, that means Obsidian believes the pane to already exist somewhere. In which case we'll need to do some debugging.
