### ISSUE TITLE
There seems to be a rouge console.log in feedParser.ts

### ISSUE THREAD

**Issue by saiyalamarty** [chhoumann/PodNotes#62]
Started seeing a lot of log statements in the dev tools console after updating to 2.4.3.

This line seems to be culprit: https://github.com/chhoumann/PodNotes/blob/master/src/parser/feedParser.ts#L114

<img width="882" alt="image" src="https://user-images.githubusercontent.com/62074202/217150436-e92b84a0-aa75-4024-ae0f-0df57b503725.png">

**Comment by chhoumann** [comment]
Thank you, @saiyalamarty! Seems I missed that after my last build. Just removed it in the latest build.
