### ISSUE TITLE
podcast-link doesn't consider timestamp

### ISSUE THREAD

**Issue by SchluppiBobbz** [chhoumann/PodNotes#65]
HI,
Thanks for this wonderful plugin!

I implemented the quick-add workflow from the docs.
Everything is working fine except that podcast-links don't consider the time-stamp. They open the right episode but instead of the timestamps' time it starts from the last play-time.

Any idea what I might have done wrong?

Best,
Hannes

**Comment by chhoumann** [comment]
Hi Hannes,

Am I understanding correctly that, after clicking a timestamp, it goes to the correct episode, but not the correct time in that episode?
What happens if you click on a timestamp more than once?

**Comment by SchluppiBobbz** [comment]
> Hi Hannes,
> 
> Am I understanding correctly that, after clicking a timestamp, it goes to the correct episode, but not the correct time in that episode? What happens if you click on a timestamp more than once?

Thats correct.
Nothing happens when I click more than once.

**Comment by chhoumann** [comment]
Should be resolved now. Thank you!

Please do update me in case it still isn't working after updating.

**Comment by SchluppiBobbz** [comment]
Works perfectly, Thanks for the ultra-quick solution!
