### ISSUE TITLE
Unable to export PodNotes_export.opml

### ISSUE THREAD

**Issue by ceccadroid** [chhoumann/PodNotes#66]
Hi!
Both under Android and Windows I'm unable to export the podcast list.
I get an indication to check the console but I haven't found nothing (at least nothing that I can relate to this problem).

Tried to uninstall and reinstall the plugin but still have the same problem.

What can I do?

**Comment by chhoumann** [comment]
Hi @ceccadroid

Do you, by chance, already have a file called `PodNotes_Export.opml` in your vault? This could cause the file creation to fail.
Does PodNotes not say anything in your console?

**Comment by ceccadroid** [comment]
Yes, this file is already in my vault. 
Removing this file let me create a new one.
Sorry but I'm unable to understand something from the console: I have so much to learn :)
Now I have to check why indicate an export of 6 feeds but show only 4 icons (at least one can be a stream from SoundCloud that apparently is not "working")
Thanks for pointing me in the right direction.

**Comment by chhoumann** [comment]
No worries! I think this is an oversight on my part. I've fixed the error message to include details about why it's failing.

I decided that exporting would not override the existing file, but should have communicated that through proper error messages.

Regarding the 6 exported feeds:
If you give me the file, I can check it out. Might be a duplicate or something.

**Comment by ceccadroid** [comment]
Thanks a lot @chhoumann !
Regarding the file I prefer to check by myself: I wish to learn something new.
In case of need I'll send you my opml for you to investigate

**Comment by chhoumann** [comment]
Sure thing :)
Always great to learn something new.

I'll close this issue then, but please don't hesitate to open a new one if you encounter issues in the future.
