### ISSUE TITLE
The podcast playback interface cannot be adjusted adaptively

### ISSUE THREAD

**Issue by EliDoves** [chhoumann/PodNotes#67]
Hello! Dear developer, Podnotes is a very useful plugin, which is exactly what I need, thank you very much for developing it!
During my use, I found a problem that may need to be improved. The podcast playback interface cannot be automatically adjusted to fit the size of the window with the adjustment of the sidebar. If the window is enlarged, the window of the entire editing area will be squeezed. Could this be optimized? Greatful!
![|300](https://user-images.githubusercontent.com/51412618/221072830-770ea083-ffd5-4a39-a7e0-b86e50362398.png)

[Video](https://youtu.be/EnGLOlGO7b8)

**Comment by chhoumann** [comment]
Hey! Super glad to hear you're liking the plugin. I've made some stylistic changes which should fix most of this :)

**Comment by EliDoves** [comment]
> Hey! Super glad to hear you're liking the plugin. I've made some stylistic changes which should fix most of this :)

Really unbelievable, such a fast speed, really thank you! I wish you have a nice day!
