### ISSUE TITLE
Specific podcast is already 'added' but cannot be removed

### ISSUE THREAD

**Issue by fixedzzz** [chhoumann/PodNotes#68]
Having this issue on Windows 10 with a brand new install of PodNotes - I'm able to replicate in multiple vaults and on Android, and confirmed a friend has the same issue.

![image](https://user-images.githubusercontent.com/6273986/221319259-41fc2e80-4501-4ddf-9dba-e4daf189f68c.png)

Clicking 'Remove' does nothing on Windows or Android, but the button works fine on other podcasts including the other two that come up when you search for 'Honestly'.

**Comment by keerah** [comment]
Having the same issue on Windows

**Comment by chhoumann** [comment]
Hey @fixedzzz & @keerah 

Thank you for reporting this! Was pretty fast to diagnose with the info you provided. Thanks.
Pushed a fix, which should be live in a few minutes :)
