### ISSUE TITLE
[feature] current time in podcast as command palette

### ISSUE THREAD

**Issue by danieltomasz** [chhoumann/PodNotes#7]
Great idea for plugin! I wonder if would be possible to add 
`getPodcastTimeFormatted(format: string, linkify?: boolean)` as a command in palette by default

**Comment by chhoumann** [comment]
Thank you, @danieltomasz! That's a great idea.

I'm planning to flesh out how the plugin should interact with notes. I'll def. include this feature in the plans.

**Comment by chhoumann** [comment]
Added native support in 1.11.0. :)

https://chhoumann.github.io/PodNotes/timestamps/
