### ISSUE TITLE
Mobile toolbar icons

### ISSUE THREAD

**Issue by Bearsaerker** [chhoumann/PodNotes#73]
I love the addon sofar. It is one of the best things in Obsidian. One thing which would be a tiny, but necessary improvement: adding little icons for the mobile toolbar. I have "capture timestamp" and both skipping features in my toolbar, but they are displayed as "?". I think it wouldn't take much to implement tiny icons for that and it would really improve the usability in a mobile scenario!

**Comment by chhoumann** [comment]
Hey @Bearsaerker, I'm glad to hear you like PodNotes! I absolutely agree this is an important UX improvement, so I've gone ahead and added it. It's available in the latest release.
