### ISSUE TITLE
Unable to find podcast player in Obsidian in iOS

### ISSUE THREAD

**Issue by EpicPilgrim** [chhoumann/PodNotes#77]
I have Obsidian on iOS. I cannot find a way to load the Podcast player. I see the docco says this plugin is mobile-friendly. How do we use it in iOS?

**Comment by EpicPilgrim** [comment]
Update: I found it by swiping from the right and tapping the backlinks heading to bring up a list of plugins. However, "Podcast Player" is in that list 8 times now, even after removal and reinstallation of the plugin within Obsidian Settings. Why would it show up 8 times?

**Comment by chhoumann** [comment]
It appeared so many times due to code loading it but not removing it - should be fixed now!
