### ISSUE TITLE
can't see the ui

### ISSUE THREAD

**Issue by donnieparka** [chhoumann/PodNotes#85]
i installed today the plug-in added some podcasts but i can't find a way to open the ui, tried adding the show button using commander but nothing happens when i click it

**Comment by chhoumann** [comment]
Hi - it appears in your right sidebar. The icon for the player can be hidden if the sidebar isn't wide enough. Can you check if this is the case for you?

**Comment by donnieparka** [comment]
Yes thank you I found it but it's really uncomfortable in that position can
I somehow disable it there and use commander to put it somewhere else?

Il gio 3 ago 2023, 10:48 Christian Bager Bach Houmann <
***@***.***> ha scritto:

**Comment by chhoumann** [comment]
You can drag the icon wherever you want. I don't use the Commander plugin myself, so I don't know about it.

**Comment by donnieparka** [comment]
Yes but only in the bar where it's put I'd like to move it on the left
sidebar. And It looks like i can't

Il gio 3 ago 2023, 11:17 Christian Bager Bach Houmann <
***@***.***> ha scritto:
