### ISSUE TITLE
How to use "add podcast note" macro using QuickAdd

### ISSUE THREAD

**Issue by Rsose** [chhoumann/PodNotes#9]
Hi Chhoumann
I just added Timestamp capture's function is working perfectly 
but I don't get how to use "Add podcast note" I just followed [the documentation QuickAdd - PodNotes](https://chhoumann.github.io/PodNotes/QuickAdd/) still not successfully solved 

Could you please provide a better description of it?Or share an example Vault I will appreciate it
Waiting for a reply
Thanks for making this great plugin

**Comment by chhoumann** [comment]
Added feature which supports note creation with metadata and timestamping natively.

Documentation:
https://chhoumann.github.io/PodNotes/templates/

Closing this because that should make the setup for creating podcast notes easier.
