### ISSUE TITLE
Ability to fetch transcripts from Apple Podcasts

### ISSUE THREAD

**Issue by Tanzeel159** [chhoumann/PodNotes#91]
Apple Podcasts recently released support for transcripts in Podcasts . It would be great if we can fetch that from the API .

Proposed Workflow : 
1) Give an option (toggle) to fetch transcripts 
2) This can be used to get summary of a podcast episode if needed with other Quickadd LLM models 

[https://www.apple.com/newsroom/2024/03/apple-introduces-transcripts-for-apple-podcasts/](url)

**Comment by chhoumann** [comment]
Hi @Tanzeel159, thank you for suggesting this!

I'd love to have this feature, but can't find any API from iTunes that lets me grab the transcriptions.

A while back I started to implement this feature on a branch, but it would cost a lot to transcribe the episodes. Would love to query some repository that just exposes it.

**Comment by Tanzeel159** [comment]
Oh okay so they haven't implement it yet. I will keep track and share if something is useful . Thanks for the effort though for trying to implement it yourself .

**Comment by zhampu** [comment]
For info: on IPhone I tried to copy the full transcript but when paste it somewhere is just taking the beginning of the copied text

**Comment by chhoumann** [comment]
Added transcription feature in #101 via OpenAI's Whisper

**Comment by chhoumann** [comment]
I've been using it all day! Works super well. LMK if you find it useful as well, or if you have any ideas/suggestions. Closing this for now :) Just open a new issue if you have an idea / dm me.

**Comment by zhampu** [comment]
@chhoumann can you explain how to use it?

**Comment by zhampu** [comment]
@chhoumann  is giving me `[Error transcribing chunk 0] [Error transcribing chunk 1] [Error transcribing chunk 2]` although I put an API key

**Comment by chhoumann** [comment]
@zhampu please check the developer console for more information. You can access it with Ctrl+Shift+i, or Cmd+Shift+i if you are on Mac. It should display the error messages there. 

Did you add billing for the OpenAI account and project?

**Comment by zhampu** [comment]
`plugin:podnotes:10235 
        
        
       POST https://api.openai.com/v1/audio/transcriptions 429 (Too Many Requests)`

**Comment by chhoumann** [comment]
The error 429 means "Too many requests," so it sounds like you've reached a rate limit for how much you can send to the OpenAI API. Waiting for a few moments resolves the issue.

**Comment by zhampu** [comment]
<img width="766" alt="Screenshot 2024-08-22 at 19 27 41" src="https://github.com/user-attachments/assets/fe20cb39-2b0f-4507-83c6-ad8b8bf7d500">
When I click on the command to transcribe a podcast, sometimes it takes the episode title from the one im listening but transcribe the previous one I transcribed

any way to fix this?
